name: Deploy to EC2 via CodeDeploy

on:
  push:
    branches:
      - main # main 브런치

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create deployment package (zip)
        run: |
          ZIP_NAME=deploy-${{ github.sha }}.zip
          cd app
          zip -r ../$ZIP_NAME . -x "*.git*"
          cd ..
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
      
      - name: Upload to S3
        run: |
          aws s3 cp $ZIP_NAME s3://${{ secrets.AWS_S3_BUCKET }}/$ZIP_NAME

      - name: Deploy using CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
            --deployment-group-name ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP }} \
            --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=zip,key=$ZIP_NAME \
            --file-exists-behavior OVERWRITE \
            --deployment-config-name CodeDeployDefault.AllAtOnce
