name: Deploy to EC2 via CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 using CodeDeploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Zip source files
        run: zip -r app.zip .

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: .
          DEST_DIR: /app

      - name: Trigger CodeDeploy
        uses: webfactory/create-aws-codedeploy-deployment@v1
        with:
          application-name: your-codedeploy-app-name
          deployment-group: your-deployment-group-name
          deployment-config: CodeDeployDefault.OneAtATime
          s3-bucket: ${{ secrets.S3_BUCKET }}
          s3-key: app.zip
          bundle-type: zip
        env:
          AWS_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
